### ISSUE TITLE
Concern about StyleMelgan losses

### ISSUE THREAD

**Issue by skol101** [kan-bayashi/ParallelWaveGAN#331]
Hello,

I'm training StyleMelGan on a 20 subset selection of VCTK (source has silence, but config has trim_silence:true) speakers . Though vocoder predictions tests are pretty good at 400k, but they aren't the greatest. 

Shall I still train any further, tough? 
![Screenshot from 2022-02-15 19-25-02](https://user-images.githubusercontent.com/53978091/154115822-d114fbed-08f4-42d6-bccb-c26cf0f4ea6e.png)
![Screenshot from 2022-02-15 19-25-23](https://user-images.githubusercontent.com/53978091/154115824-e1fc2c64-1ac4-4a4b-abd5-a374692aae6d.png)

configuration file
```
allow_cache: true
batch_max_steps: 24000
batch_size: 8
config: conf/style_melgan.v2.yaml
dev_dumpdir: dump/dev/raw
dev_feats_scp: null
dev_segments: null
dev_wav_scp: null
discriminator_adv_loss_params:
  average_by_discriminators: false
discriminator_grad_norm: -1
discriminator_optimizer_params:
  betas:
  - 0.5
  - 0.9
  lr: 0.0002
  weight_decay: 0.0
discriminator_optimizer_type: Adam
discriminator_params:
  discriminator_params:
    bias: true
    channels: 16
    downsample_scales:
    - 4
    - 4
    - 4
    - 1
    kernel_sizes:
    - 5
    - 3
    max_downsample_channels: 512
    nonlinear_activation: LeakyReLU
    nonlinear_activation_params:
      negative_slope: 0.2
    out_channels: 1
  pqmf_params:
  - - 1
    - None
    - None
    - None
  - - 2
    - 62
    - 0.267
    - 9.0
  - - 4
    - 62
    - 0.142
    - 9.0
  - - 8
    - 62
    - 0.07949
    - 9.0
  repeats: 4
  use_weight_norm: true
  window_sizes:
  - 512
  - 1024
  - 2048
  - 4096
discriminator_scheduler_params:
  gamma: 0.5
  milestones:
  - 200000
  - 400000
  - 600000
  - 800000
discriminator_scheduler_type: MultiStepLR
discriminator_train_start_steps: 100000
discriminator_type: StyleMelGANDiscriminator
distributed: true
eval_interval_steps: 1000
fft_size: 2048
fmax: 7600
fmin: 80
format: hdf5
generator_adv_loss_params:
  average_by_discriminators: false
generator_grad_norm: -1
generator_optimizer_params:
  betas:
  - 0.5
  - 0.9
  lr: 0.0001
  weight_decay: 0.0
generator_optimizer_type: Adam
generator_params:
  aux_channels: 80
  bias: true
  channels: 64
  dilation: 2
  gated_function: softmax
  in_channels: 128
  kernel_size: 9
  noise_upsample_activation: LeakyReLU
  noise_upsample_activation_params:
    negative_slope: 0.2
  noise_upsample_scales:
  - 10
  - 2
  - 2
  - 2
  out_channels: 1
  upsample_mode: nearest
  upsample_scales:
  - 5
  - 1
  - 5
  - 1
  - 3
  - 1
  - 2
  - 2
  - 1
  use_weight_norm: true
generator_scheduler_params:
  gamma: 0.5
  milestones:
  - 100000
  - 300000
  - 500000
  - 700000
  - 900000
generator_scheduler_type: MultiStepLR
generator_type: StyleMelGANGenerator
global_gain_scale: 1.0
hop_size: 300
lambda_adv: 1.0
lambda_aux: 1.0
log_interval_steps: 100
num_mels: 80
num_save_intermediate_results: 4
num_workers: 2
outdir: exp/train_nodev_style_melgan.v2
pin_memory: true
pretrain: ''
rank: 1
remove_short_samples: false
resume: exp/train_nodev_style_melgan.v2/checkpoint-402044steps.pkl
sampling_rate: 24000
save_interval_steps: 50000
stft_loss_params:
  fft_sizes:
  - 1024
  - 2048
  - 512
  hop_sizes:
  - 120
  - 240
  - 50
  win_lengths:
  - 600
  - 1200
  - 240
  window: hann_window
train_dumpdir: dump/train_nodev/raw
train_feats_scp: null
train_max_steps: 1500000
train_segments: null
train_wav_scp: null
trim_frame_size: 1024
trim_hop_size: 256
trim_silence: true
trim_threshold_in_db: 60
verbose: 1
version: 0.5.4
win_length: 1200
window: hann
world_size: 2
```

Here's groundspeech vs generated comparison 
![2](https://user-images.githubusercontent.com/53978091/154116614-6ffb279c-ccd4-466c-9dea-72cee0ab9d9a.png)
