### ISSUE TITLE
Generator exploded after ~138K iters.

### ISSUE THREAD

**Issue by erogol** [kan-bayashi/ParallelWaveGAN#61]
I observed a interesting behaviour after 138K iters where discriminator dominated the training and generator exploded in  both train and validation losses. Do you have any idea why and how to prevent it?

I am training on LJSpeech and I basically use the same learning schedule you released with the v2 config for LJSpeech. (Train generator until 100K and enable the discriminator)

Here is the tensorboard screenshot.

![image](https://user-images.githubusercontent.com/1402048/73440347-6d192d80-4351-11ea-9eaa-aace0a0b9baa.png)

**Comment by kan-bayashi** [comment]
Hi @erogol.
I also met this problem. I am trying to solve now (#54). You can see our discussion in (https://github.com/kan-bayashi/ParallelWaveGAN/issues/27#issuecomment-574457093).
The things I tried are as follows:
- Use a large batchsize (according to @Rayhane-mamah)
  But batchsize 10 and 20 also caused this problem.
- Use halved LR for discriminator
  This can prevent it but the discriminator gradually became stronger and the quality results are not so good.

**Comment by erogol** [comment]
A short literature review gave me these options if they make any sense;

- Label Smoothing at Discriminator.
- Setting lower LR for Generator.
- Adding noise to Discriminator input.
- Larger LR for D and Smaller LR for G
    - 0.0004 and 0.0001

Have you tried anything similar to these, so I can try the rest maybe.

**Comment by dathudeptrai** [comment]
@erogol @kan-bayashi hi, use transpose convolution rather than Upsampling on generator will help (use kernel_size and stride large enough). I'm combine melgan and parallel wave gan as this discussion #46 , the result seem very good for me.

**Comment by erogol** [comment]
@dathudeptrai merging the models only architecturally or training methods as well?

**Comment by dathudeptrai** [comment]
@erogol both, i use training method on this repo (V2 as u are using).

**Comment by kan-bayashi** [comment]
That is interesting.
I will add MelGAN generator in this weekend.

**Comment by dathudeptrai** [comment]
keep in mind that all GAN arch, the author has tuned the parameters and arch carefully (generator won't stronger than discriminator and vice versar). In ur config, u don't use the original discriminator (u use residualdiscriminator instead), and that make the discriminator stronger, u need to modify generator too :D.

**Comment by kan-bayashi** [comment]
I added MelGAN generator in #62.
Training is on going :D

**Comment by dathudeptrai** [comment]
@kan-bayashi wow, very fast :)), the training progress will 5x faster than Parallelwavegan :D, let see

**Comment by kan-bayashi** [comment]
I added initial MelGAN results #65 (v1 config based).
The results seem to be reasonable and there is a room for improvement if we continue to train more iterations (the iterations are ongoing).
I'm also trying v2-based MelGAN (ongoing). Please looking forward to seeing the results.

**Comment by dathudeptrai** [comment]
@kan-bayashi let see, i’m training melgan (almost same as u are doing) with fake quantization training 8bit. Also i convert it successfully to tflite, the inference time on cpu mobile 1 thread is around 2x faster than real time.

**Comment by kan-bayashi** [comment]
@dathudeptrai 
You mean this feature?
https://pytorch.org/docs/stable/quantization.html#torch.quantization.FakeQuantize
That's is amazing! Real-time generation on the device come true :D

**Comment by dathudeptrai** [comment]
@kan-bayashi No, i use this https://github.com/Xilinx/brevitas (need to expands input to 4D), this frame work just support conv2D :D. but it's enough :D. Al so i have a larger version of melgan generator then i convert it to tensorflow and use tensorrt to optimize it on server side :D. Seem all we need to do now is enhance the quality :)), the speed isn't a problem anymore :D

**Comment by erogol** [comment]
I can tell, even though there is a jump after 100K, still voice fdellity improves as the training goes. It is interesting to see.

**Comment by dathudeptrai** [comment]
@erogol, ONNX is the way u can try, but according to my experience, loading weights with the same architecture is the best :)), i can implement both torch and tf very fast :D. And offcourse, when u use TF, u can ez to convert it into tflite and tensorrt to optimize. I don't really like use intermediate representation like ONNX because the limitted support operator :D

**Comment by erogol** [comment]
I successfully trained MelGAN (Generator) in my fork. MelGAN requires the v1 (smaller), discriminator. I guess larger D is too strong for MelGAN to learn.

You can check the model with TTS here:
https://colab.research.google.com/drive/1Zg9jR27Pr-ziVa0krjtdoy2dKv6whv7b

There is still a slight background noise but it is because of the TTS model. Somehow, GAN models are not as robust as WaveRNN to spectrogram representation. Maybe it is a good idea to induce some random noise in training.

**Comment by dathudeptrai** [comment]
@erogol pls try ratios = [4,4,4,2,2] and increase n_réidual, maybe it can help u eliminate background nóie :D

**Comment by kan-bayashi** [comment]
Currently, I tried to train the MelGAN generator with
- residual discriminator (v2-based)
- MelGAN discriminator

The training curve is not stable but it sounds more natural than v1.
Once I finished the training, I will upload the config and resutls.

**Comment by kan-bayashi** [comment]
> pls try ratios = [4,4,4,2,2] and increase n_réidual, maybe it can help u eliminate background nóie :D

That's nice.
I will try the following config.
```yaml
generator_type: "MelGANGenerator" # Generator type.
generator_params:
    in_channels: 80                  # Number of input channels.
    out_channels: 1                  # Number of output channels.
    kernel_size: 7                   # Kernel size of initial and final conv layers.
    channels: 1024                   # Initial number of channels for conv layers.
    upsample_scales: [4, 4, 2, 2, 2] # List of Upsampling scales.
    stack_kernel_size: 3             # Kernel size of dilated conv layers in residual stack.
    stacks: 4                        # Number of stacks in a single residual stack module.
    use_weight_norm: True            # Whether to use weight normalization.
    use_causal_conv: False           # Whether to use causal convolution.
```
